### ISSUE TITLE
Table of contents links on getpocket.com/en/tos/ are broken

### ISSUE THREAD

**Issue by oopdahl** [mozmeao/pocket-marketing-pages#18]
**Issue:**
The table of contents links on our Terms of Service page are each broken: https://getpocket.com/en/tos/

This can be reproduced in Firefox and Chrome, looks to be occurring regardless of browser.

**Steps to reproduce:**
1. Open Pocket TOS page, linked here (https://getpocket.com/en/tos/)
2. Click any of the underlined section headers

**Expected result:**
User is directed to corresponding section on the TOS page

**Actual result:**
User is directed to "how can I help?" generic Pocket error page

**Comment by pmac** [comment]
I've pushed this fix to production as well. Should be working properly in the next few minutes.
