### ISSUE TITLE
Add convert.com to learnmore page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozmeao/pocket-marketing-pages#4]
We are ready to get started on testing and optimizing key pocket pages that have been converted to marketing pages.

from contentful: Code snippet should be in the <head> section, just after </title>, on all experience and goal pages. [Read More](https://convert.zendesk.com/hc/en-us/articles/205152665-Targeting-with-Advanced-Page-Tagging).

here is the basic code snippet:

```
<!-- begin Convert Experiences code--> 
<script type="text/javascript" src="https://cdn-3.convertexperiments.com/js/10039-10033300.js"></script> 
<!-- end Convert Experiences code -->
```

or advanced:

```
<!--begin Convert Experiences code-->
<script type="text/javascript">
<!--fill in the values for the variables that you want to use-->
var _conv_page_type = "";
var _conv_category_id = "";
var _conv_category_name = "";
var _conv_product_sku = "";
var _conv_product_name = "";
var _conv_product_price = "";
var _conv_customer_id = "";
var _conv_custom_v1 = "";
var _conv_custom_v2 = "";
var _conv_custom_v3 = "";
var _conv_custom_v4 = "";
<!--end of editing here>
</script>
<script type="text/javascript" src="https://cdn-3.convertexperiments.com/js/10039-10033300.js"></script>
<!-- end Convert Experiences code -->
```

**Comment by slightlyoffbeat** [comment]
For this initial test, we can target https://getpocket.com/en/firefox/new_tab_learn_more/

I think we should only put convert.com code on the pages we plan to test on. For now that would only be the en new_tab_learn_more page

**Comment by pmac** [comment]
This is done right?

**Comment by slightlyoffbeat** [comment]
Yes. Done and closing.
